Docs final feedback
soundxyz/docs pull request #27
Opened 2022-11-11 17:21 UTC by gigamesh

2022-11-12 02:46 UTC, saihaj requested changes
Too much margin on iPhone 14 pro 
![79019283-33FF-452C-AE78-0B7D42F5EF21](https://user-images.githubusercontent.com/44710980/201453060-a7ad914c-5dd5-443e-9948-32908769fcd6.jpeg)

2022-11-12 20:29 UTC, gigamesh commented
> Too much margin on iPhone 14 pro ![79019283-33FF-452C-AE78-0B7D42F5EF21](https://user-images.githubusercontent.com/44710980/201453060-a7ad914c-5dd5-443e-9948-32908769fcd6.jpeg)

@saihaj fixed 👍

2022-11-12 20:55 UTC, saihaj approved these changes

2022-11-14 23:33 UTC, gigamesh commented on components/HeaderLogo.tsx
> +  const isDarkMode = useIsDarkMode(router.pathname === '/')
override example

2022-11-16 04:58 UTC, vigneshka approved these changes

2022-11-17 17:47 UTC, merged